apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: cabpk-controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: cabpk-controller-manager
spec:
  selector:
    matchLabels:
      control-plane: cabpk-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: cabpk-controller-manager
    spec:
      containers:
      - image: controller:latest
        imagePullPolicy: Always
        name: manager
      terminationGracePeriodSeconds: 10
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
